### PR TITLE
feat: added dark Theme

### PR DESCRIPTION
**Pull request by kunalkumar007**
Count it as my contribution to hacktoberfest 😇 #6

### CODE REVIEW

**Review by saglaniharsh — CHANGES_REQUESTED** [review]
1) This does not work on MyStory and Project page
2) Content isn't readable. For ex. icons and text that is in black or grey.
3) You'll need to include an icon in the project's page.

**Comment by kunalkumar007** [comment]
Hy @ashawe Can you please check and Let me know further.

**Comment by kunalkumar007** [comment]
When accepted the PR must have the label hacktoberfest-accepted to count for the participants.

**Review by saglaniharsh — CHANGES_REQUESTED** [review]
0) Please pull the latest changes from the gh-pages branch so there's no conflict when we merge this pr.
1) All the "View all", "View Project", "See Certificate" and social media (connect section) Links are still black.
The intro in the start - "Undergrad ..." still isn't visible.
2) Please change the icon to a "sun" icon when its in dark mode.

**Comment by kunalkumar007** [comment]
Hy @ashawe, I have made the changes, please review and don't forget when you accepted the PR, it must have the label hacktoberfest-accepted to count for the participants. 😇

**Review by saglaniharsh — CHANGES_REQUESTED** [review]
Please add a cursor:pointer to them

**Comment by kunalkumar007** [comment]
I think you mean cursor property to the sun icon 🤔. please confirm after seeing the last change.

**Review by saglaniharsh — APPROVED** [review]

**Pull request merged**
